//
// Created by a on 7/6/20.
//

#ifndef DNAANALYZERPROJECT_PARSINGPARAMSFACTORY_H
#define DNAANALYZERPROJECT_PARSINGPARAMSFACTORY_H


class ParsingParamsFactory {

};


#endif //DNAANALYZERPROJECT_PARSINGPARAMSFACTORY_H
